name = "Concatenation"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33df8f0eb8a5dcb241bb5b2707638821b3f054b509650f6a00ce81600c12ad51"

[versions]
fabric = "0.92.2"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
