name = "Concatenation"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9c2bb38a5a29484bfd50342e45ae5b8e2542cc904758611b082a9e80b6ddfde"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
