name = "Concatenation"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5429a66d0151ea86339ff1b5fbedd8ce54d407fabeb18b3042c9cd84f1e0e0d"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
